apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ipa2025-msapp-scheduler
  namespace: argocd
spec:
  project: ipa2025
  source:
    repoURL: 'https://github.com/kxxnD04/ipa2025-msapp'
    targetRevision: HEAD
    path: scheduler/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ipa2025
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
